### PR TITLE
merge to common scripts

### PR DESCRIPTION
**Pull request by knorth55**
this PR merge the xml script to `common/scripts`.
@fanshi14 @iory can you check this PR?

### CODE REVIEW

**Comment by fanshi14** [comment]
@knorth55 Thank you very much! I have one question, is there any real functionality for common scripts? Are they just for reference?

**Comment by knorth55** [comment]
I merge xml function to `common/scripts`, and now `XML` and `LabelMe` example use the same scripts.

**Comment by knorth55** [comment]
@fanshi14 so can you try training your xml dataset with this PR?

**Comment by fanshi14** [comment]
> @fanshi14 so can you try training your xml dataset with this PR?

Danke! I see, I'll try tomorrow.

**Comment by fanshi14** [comment]
@knorth55 It works perfectly w/o any problem. Thank you very much for the great organization!

**Pull request merged**
